---
title: "US COVID19 Trends"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=FALSE, include=FALSE}

#----------------------------------------------------
# Pulling the coronvirus data from John Hopkins repo
# https://github.com/CSSEGISandData/COVID-19
#----------------------------------------------------
# Setting functions
`%>%` <- magrittr::`%>%`
#----------------------------------------------------
# Pulling confirmed cases

raw_conf <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv",
                     stringsAsFactors = FALSE)

lapply(1:ncol(raw_conf), function(i){
  if(all(is.na(raw_conf[, i]))){
    raw_conf <<- raw_conf[, -i]
    return(print(paste("Column", names(raw_conf)[i], "is missing", sep = " ")))
  } else {
    return(NULL)
  }
})
# Fixing US data
# Aggregating county level to state level

raw_us_conf <- raw_conf %>%
  dplyr::filter(Country.Region == "US") %>%
  dplyr::mutate(state = ifelse(!grepl(",", Province.State),
                               Province.State,
                               trimws(substr(Province.State,
                                             regexpr(",", Province.State) + 1,
                                             regexpr(",", Province.State) + 3)))) %>%
  dplyr::left_join(data.frame(state = state.abb,
                              state_name = state.name,
                              stringsAsFactors = FALSE),
                   by = "state") %>%
  dplyr::mutate(state_name = ifelse(is.na(state_name), state, state_name)) %>%
  dplyr::mutate(state_name = ifelse(state_name == "D.", "Washington, D.C.", state_name)) %>%
  dplyr::mutate(Province.State = state_name) %>%
  dplyr::select(-state, -state_name)

raw_us_map <- raw_us_conf %>%
  dplyr::select("Province.State","Country.Region", "Lat", "Long") %>%
  dplyr::distinct() %>%
  dplyr::mutate(dup = duplicated(Province.State)) %>%
  dplyr::filter(dup == FALSE) %>%
  dplyr::select(-dup)

us_agg_conf <- aggregate(x = raw_us_conf[, 5:(ncol(raw_us_conf))], by = list(raw_us_conf$Province.State), FUN = sum) %>%
  dplyr::select(Province.State = Group.1, dplyr::everything())

us_fix_conf <- raw_us_map %>% dplyr::left_join(us_agg_conf, by = "Province.State")


raw_conf1 <- raw_conf %>%
  dplyr::filter(Country.Region != "US") %>%
  dplyr::bind_rows(us_fix_conf)



# Transforming the data from wide to long
# Creating new data frame
df_conf <- raw_conf1[, 1:4]

for(i in 5:ncol(raw_conf1)){
  
  raw_conf1[,i] <- as.integer(raw_conf1[,i])
  # raw_conf[,i] <- ifelse(is.na(raw_conf[, i]), 0 , raw_conf[, i])
  print(names(raw_conf1)[i])
  
  if(i == 5){
    df_conf[[names(raw_conf1)[i]]] <- raw_conf1[, i]
  } else {
    df_conf[[names(raw_conf1)[i]]] <- raw_conf1[, i] - raw_conf1[, i - 1]
  }
  
  
}


df_conf1 <-  df_conf %>% tidyr::pivot_longer(cols = dplyr::starts_with("X"),
                                             names_to = "date_temp",
                                             values_to = "cases_temp")

# Parsing the date
df_conf1$month <- sub("X", "",
                      strsplit(df_conf1$date_temp, split = "\\.") %>%
                        purrr::map_chr(~.x[1]) )

df_conf1$day <- strsplit(df_conf1$date_temp, split = "\\.") %>%
  purrr::map_chr(~.x[2])


df_conf1$date <- as.Date(paste("2020", df_conf1$month, df_conf1$day, sep = "-"))

# Aggregate the data to daily
df_conf2 <- df_conf1 %>%
  dplyr::group_by(Province.State, Country.Region, Lat, Long, date) %>%
  dplyr::summarise(cases = sum(cases_temp)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(type = "confirmed",
                Country.Region = trimws(Country.Region),
                Province.State = trimws(Province.State))

head(df_conf2)
tail(df_conf2)
#----------------------------------------------------
# Pulling death cases

raw_death <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv",
                      stringsAsFactors = FALSE,
                      fill =FALSE)

lapply(1:ncol(raw_death), function(i){
  if(all(is.na(raw_death[, i]))){
    raw_death <<- raw_death[, -i]
    return(print(paste("Column", names(raw_death)[i], "is missing", sep = " ")))
  } else {
    return(NULL)
  }
})
# Fixing US data
# Aggregating county level to state level

raw_us_death <- raw_death %>%
  dplyr::filter(Country.Region == "US") %>%
  dplyr::mutate(state = ifelse(!grepl(",", Province.State),
                               Province.State,
                               trimws(substr(Province.State,
                                             regexpr(",", Province.State) + 1,
                                             regexpr(",", Province.State) + 3)))) %>%
  dplyr::left_join(data.frame(state = state.abb,
                              state_name = state.name,
                              stringsAsFactors = FALSE),
                   by = "state") %>%
  dplyr::mutate(state_name = ifelse(is.na(state_name), state, state_name)) %>%
  dplyr::mutate(state_name = ifelse(state_name == "D.", "Washington, D.C.", state_name)) %>%
  dplyr::mutate(Province.State = state_name) %>%
  dplyr::select(-state, -state_name)

# raw_us_map <- raw_us_death %>%
#   dplyr::select("Province.State","Country.Region", "Lat", "Long") %>%
#   dplyr::distinct() %>%
#   dplyr::mutate(dup = duplicated(Province.State)) %>%
#   dplyr::filter(dup == FALSE) %>%
#   dplyr::select(-dup)

us_agg_death <- aggregate(x = raw_us_death[, 5:(ncol(raw_us_death))], by = list(raw_us_death$Province.State), FUN = sum) %>%
  dplyr::select(Province.State = Group.1, dplyr::everything())

us_fix_death <- raw_us_map %>% dplyr::left_join(us_agg_death, by = "Province.State")


raw_death1 <- raw_death %>%
  dplyr::filter(Country.Region != "US") %>%
  dplyr::bind_rows(us_fix_death)





# Transforming the data from wide to long
# Creating new data frame
df_death <- raw_death1[, 1:4]

for(i in 5:ncol(raw_death1)){
  print(i)
  raw_death1[,i] <- as.integer(raw_death1[,i])
  raw_death1[,i] <- ifelse(is.na(raw_death1[, i]), 0 , raw_death1[, i])
  
  if(i == 5){
    df_death[[names(raw_death1)[i]]] <- raw_death1[, i]
  } else {
    df_death[[names(raw_death1)[i]]] <- raw_death1[, i] - raw_death1[, i - 1]
  }
}


df_death1 <-  df_death %>% tidyr::pivot_longer(cols = dplyr::starts_with("X"),
                                               names_to = "date_temp",
                                               values_to = "cases_temp")

# Parsing the date
df_death1$month <- sub("X", "",
                       strsplit(df_death1$date_temp, split = "\\.") %>%
                         purrr::map_chr(~.x[1]) )

df_death1$day <- strsplit(df_death1$date_temp, split = "\\.") %>%
  purrr::map_chr(~.x[2])


df_death1$date <- as.Date(paste("2020", df_death1$month, df_death1$day, sep = "-"))

# Aggregate the data to daily
df_death2 <- df_death1 %>%
  dplyr::group_by(Province.State, Country.Region, Lat, Long, date) %>%
  dplyr::summarise(cases = sum(cases_temp)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(type = "death",
                Country.Region = trimws(Country.Region),
                Province.State = trimws(Province.State))

head(df_death2)
tail(df_death2)
#----------------------------------------------------
# Pulling recovered cases

raw_rec <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv",
                    stringsAsFactors = FALSE,
                    fill =FALSE)

lapply(1:ncol(raw_rec), function(i){
  if(all(is.na(raw_rec[, i]))){
    raw_rec <<- raw_rec[, -i]
    return(print(paste("Column", names(raw_rec)[i], "is missing", sep = " ")))
  } else {
    return(NULL)
  }
})
# Fixing US data
# Aggregating county level to state level

raw_us_rec <- raw_rec %>%
  dplyr::filter(Country.Region == "US") %>%
  dplyr::mutate(state = ifelse(!grepl(",", Province.State),
                               Province.State,
                               trimws(substr(Province.State,
                                             regexpr(",", Province.State) + 1,
                                             regexpr(",", Province.State) + 3)))) %>%
  dplyr::left_join(data.frame(state = state.abb,
                              state_name = state.name,
                              stringsAsFactors = FALSE),
                   by = "state") %>%
  dplyr::mutate(state_name = ifelse(is.na(state_name), state, state_name)) %>%
  dplyr::mutate(state_name = ifelse(state_name == "D.", "Washington, D.C.", state_name)) %>%
  dplyr::mutate(Province.State = state_name) %>%
  dplyr::select(-state, -state_name)

raw_us_map <- raw_us_rec %>%
  dplyr::select("Province.State","Country.Region", "Lat", "Long") %>%
  dplyr::distinct() %>%
  dplyr::mutate(dup = duplicated(Province.State)) %>%
  dplyr::filter(dup == FALSE) %>%
  dplyr::select(-dup)

us_agg_rec <- aggregate(x = raw_us_rec[, 5:(ncol(raw_us_rec))], by = list(raw_us_rec$Province.State), FUN = sum) %>%
  dplyr::select(Province.State = Group.1, dplyr::everything())

us_fix_rec <- raw_us_map %>% dplyr::left_join(us_agg_rec, by = "Province.State")


raw_rec1 <- raw_rec %>%
  dplyr::filter(Country.Region != "US") %>%
  dplyr::bind_rows(us_fix_rec)




# Transforming the data from wide to long
# Creating new data frame
df_rec <- raw_rec1[, 1:4]

for(i in 5:ncol(raw_rec1)){
  print(i)
  raw_rec1[,i] <- as.integer(raw_rec1[,i])
  raw_rec1[,i] <- ifelse(is.na(raw_rec1[, i]), 0 , raw_rec1[, i])
  
  if(i == 5){
    df_rec[[names(raw_rec1)[i]]] <- raw_rec1[, i]
  } else {
    df_rec[[names(raw_rec1)[i]]] <- raw_rec1[, i] - raw_rec1[, i - 1]
  }
}


df_rec1 <-  df_rec %>% tidyr::pivot_longer(cols = dplyr::starts_with("X"),
                                           names_to = "date_temp",
                                           values_to = "cases_temp")

# Parsing the date
df_rec1$month <- sub("X", "",
                     strsplit(df_rec1$date_temp, split = "\\.") %>%
                       purrr::map_chr(~.x[1]) )

df_rec1$day <- strsplit(df_rec1$date_temp, split = "\\.") %>%
  purrr::map_chr(~.x[2])


df_rec1$date <- as.Date(paste("2020", df_rec1$month, df_rec1$day, sep = "-"))

# Aggregate the data to daily
df_rec2 <- df_rec1 %>%
  dplyr::group_by(Province.State, Country.Region, Lat, Long, date) %>%
  dplyr::summarise(cases = sum(cases_temp)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(type = "recovered",
                Country.Region = trimws(Country.Region),
                Province.State = trimws(Province.State))

head(df_rec2)
tail(df_rec2)
#---------------- Aggregate all cases ----------------

#
coronavirus <- dplyr::bind_rows(df_conf2, df_death2, df_rec2) %>%
  as.data.frame()



head(coronavirus)
tail(coronavirus)

rm(list= ls()[! (ls() %in% c('coronavirus'))])

```

```{r, echo=FALSE,include=FALSE}

library(ggplot2)
library(dplyr)
```


## US Analysis 

```{r, echo = FALSE, include=TRUE}


us_all = coronavirus %>% filter(Country.Region == "US")
us_d = us_all %>% filter(type == "confirmed")
us_g = us_all %>% filter(type == "death")

# Summary: overall cases, 
us_all = us_all %>% group_by(Country.Region, type) %>%
  summarise(total_cases = sum(cases)) 

us_all

#mortality rate, recov/dead ratio 
mortality_rate = as.data.frame(us_all[2,3] / us_all[1,3])
colnames(mortality_rate)[1] = "Mortality Rate"
mortality_rate

recovery_rate = as.data.frame(us_all[3,3] / us_all[2,3])
colnames(recovery_rate)[1] = "Recovery Rate"
recovery_rate


```




# US Case Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "confirmed" ) %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))

ggplot(gr, aes(x=date, y=cases), ) + geom_point() + geom_smooth() +
  labs(title = "US Case Growth",
       x = "Date",
       y = "New Cases")

gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14

gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "Case Growth Rate"
growth
  

```



# US Death Growth    



```{r, echo = FALSE, include=TRUE, warning=FALSE}
                      
gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "death" ) %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))

ggplot(gr, aes(x=date, y=cases), ) + geom_point() + geom_smooth() +
  labs(title = "US Death Growth",
       x = "Date",
       y = "New Cases")

gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14

gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "Death Growth Rate"
growth

```

# Most Cases by State
```{r, echo = FALSE, include=TRUE, warning=FALSE}

gr = coronavirus %>% filter(Country.Region == "US" & type == "confirmed") %>% 
  group_by(Province.State) %>% summarise(cases = sum(cases)) %>% arrange(desc(cases))

t10 = gr[c(1:10) ,]

t10

```


# State Growth 
```{r, echo = FALSE, include=TRUE, warning=FALSE}

t10l = t10$Province.State



df = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "confirmed" & Province.State %in% t10l) %>%
  group_by(date, Province.State) %>% 
  summarise(cases = sum(cases))


for (i in seq_along(t10l)) {

plot = ggplot(subset(df, df$Province.State==t10l[i]),aes(x=date, y=cases), ) + geom_point() + geom_smooth() +
      labs(title = "Case Growth",
       x = "Date",
       y = "New Cases") +
      facet_wrap( ~  Province.State, ncol=5)
print(plot)

}

```

# CA Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "confirmed" & Province.State == "California") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14

gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "CA Case Growth Rate"
growth


gr
```


# WA Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "confirmed" & Province.State == "Washington") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14

gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "WA Case Growth Rate"
growth

gr

```


# NY Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-01' & type == "confirmed" & Province.State == "New York") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14

gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "NY Case Growth Rate"
growth

gr


```

# FL Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-11' & type == "confirmed" & Province.State == "Florida") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14



gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "FL Case Growth Rate"
growth

gr



```

# GA Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-11' & type == "confirmed" & Province.State == "Georgia") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14



gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "GA Case Growth Rate"
growth

gr



```

# IL Growth

```{r, echo = FALSE, include=TRUE, warning=FALSE}

foc = c("New York","Washington","California")

gr = coronavirus %>% filter(Country.Region == "US" & date >= '2020-03-11' & type == "confirmed" & Province.State == "Illinois") %>%
  group_by(date) %>% 
  summarise(cases = sum(cases)) %>% mutate(diff = 1 + (cases - lag(cases))/ lag(cases)) %>% arrange(desc(date))


gr3 = sum(gr[c(1:3),3])/ 3
gr7 = sum(gr[c(1:7),3])/ 7
gr10 = sum(gr[c(1:10),3])/ 10
gr14 = sum(gr[c(1:14),3])/ 14



gr_list = c(gr3,gr7,gr10,gr14)
gr_cols = c("3 Day", "7 Day", "10 Day", "14 Day")
growth = as.data.frame(row.names =  gr_cols, gr_list)
colnames(growth)[1] = "IL Case Growth Rate"
growth

gr



```




































